# Generated by Django 5.1.3 on 2024-12-05 10:50

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='ModifiedAt')),
                ('registration_plate', models.CharField(editable=False, max_length=16, unique=True, verbose_name='RegistrationPlate')),
                ('drivers', models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Drivers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
