from server.apps.account.views.email_verification import AccountEmailVerificationView
from server.apps.account.views.email_verification_resend import AccountEmailVerificationResendView
from server.apps.account.views.register import AccountRegisterView
