from server.apps.account.views.email_verification import AccountEmailVerificationView
from server.apps.account.views.email_verification_resend import AccountEmailVerificationResendView
from server.apps.account.views.password_reset import AccountPasswordResetView
from server.apps.account.views.password_reset_confirm import AccountPasswordResetConfirmView
from server.apps.account.views.register import AccountRegisterView
