from server.apps.account.views.account_anonymize import AccountAnonymizeView
from server.apps.account.views.account_details import AccountDetailsView
from server.apps.account.views.account_modify import AccountModifyView
from server.apps.account.views.account_register import AccountRegisterView
from server.apps.account.views.email_verification import AccountEmailVerificationView
from server.apps.account.views.email_verification_resend import AccountEmailVerificationResendView
from server.apps.account.views.password_reset import AccountPasswordResetView
from server.apps.account.views.password_reset_confirm import AccountPasswordResetConfirmView
