from server.apps.camping.serializers.plot_details import CampingPlotDetailsSerializer
from server.apps.camping.serializers.section_details import CampingSectionDetailsSerializer
from server.apps.camping.serializers.section_modify import CampingSectionModifySerializer
