from server.apps.camping.serializers.payment_details import PaymentDetailsSerializer
from server.apps.camping.serializers.plot_details import CampingPlotDetailsSerializer
from server.apps.camping.serializers.reservation_create import ReservationCreateSerializer
from server.apps.camping.serializers.reservation_details import ReservationDetailsSerializer
from server.apps.camping.serializers.reservation_list_element import ReservationListElementSerializer
from server.apps.camping.serializers.reservation_modify_car import ReservationModifyCarSerializer
from server.apps.camping.serializers.section_details import CampingSectionDetailsSerializer
from server.apps.camping.serializers.section_modify import CampingSectionModifySerializer
