# Generated by Django 5.1.3 on 2025-01-05 16:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='ModifiedAt')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='Name')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='BasePrice')),
                ('price_per_adult', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='PricePerAdult')),
                ('price_per_child', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='PricePerChild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampingPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='ModifiedAt')),
                ('position', models.CharField(max_length=8, verbose_name='Position')),
                ('max_number_of_people', models.PositiveSmallIntegerField(verbose_name='MaximumNumberOfPeople')),
                ('width', models.DecimalField(decimal_places=2, help_text='PlotWidthHelpText', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Width')),
                ('length', models.DecimalField(decimal_places=2, help_text='PlotLengthHelpText', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Length')),
                ('water_connection', models.BooleanField(default=False, verbose_name='WaterConnection')),
                ('electricity_connection', models.BooleanField(default=False, verbose_name='ElectricityConnection')),
                ('is_shaded', models.BooleanField(default=False, verbose_name='IsShaded')),
                ('grey_water_discharge', models.BooleanField(default=False, verbose_name='GreyWaterDischarge')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('camping_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping_plots', to='camping.campingsection', verbose_name='CampingSection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('position', 'camping_section'), name='unique_camping_plot')],
            },
        ),
    ]
