# Generated by Django 5.1.3 on 2025-01-08 14:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='ModifiedAt')),
                ('status', models.IntegerField(choices=[(0, 'WaitingForPayment'), (1, 'Canceled'), (2, 'Unpaid'), (3, 'Paid'), (4, 'Returned')], default=0)),
                ('stripe_checkout_id', models.CharField(max_length=256, verbose_name='StripeCheckoutId')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='ModifiedAt')),
                ('date_from', models.DateField(verbose_name='DateFrom')),
                ('date_to', models.DateField(verbose_name='DateTo')),
                ('number_of_adults', models.PositiveSmallIntegerField(verbose_name='NumberOfAdults')),
                ('number_of_children', models.PositiveSmallIntegerField(verbose_name='NumberOfChildren')),
                ('comments', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Comments')),
                ('camping_plot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='camping.campingplot', verbose_name='CampingPlot')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='car.car', verbose_name='Car')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='camping.payment', verbose_name='Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
