# Generated by Django 5.1.3 on 2025-01-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_payment_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_checkout_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='StripeCheckoutId'),
        ),
    ]
