from server.business_logic.mailing.camping.contact_form import ContactFormMail
from server.business_logic.mailing.camping.contact_form_confirmation import ContactFormConfirmationMail
from server.business_logic.mailing.camping.payment_expired import PaymentExpiredMail
from server.business_logic.mailing.camping.payment_refund_processed import PaymentRefundProcessedMail
from server.business_logic.mailing.camping.payment_success import PaymentSuccessMail
from server.business_logic.mailing.camping.reservation_cancel import ReservationCancelMail
from server.business_logic.mailing.camping.reservation_create import ReservationCreateMail
from server.business_logic.mailing.camping.reservation_reminder import ReservationReminderMail
