from server.apps.camping.views.plot_availability_list import CampingPlotAvailabilityListView
from server.apps.camping.views.plot_details import CampingPlotDetailsView
from server.apps.camping.views.section_details import CampingSectionDetailsView
from server.apps.camping.views.section_modify import CampingSectionModifyView
