import os
from decimal import Decimal

# Predefined char lengths
MICRO_LENGTH = 8
TINY_LENGTH = 16
SMALL_LENGTH = 32
MEDIUM_LENGTH = 64
INTERMEDIATE_LENGTH = 128
LARGE_LENGTH = 256
XL_LENGTH = 512

PLOT_PRICE_DIGITS = 6
PRICE_DECIMAL_PLACES = 2
PRICE_MIN_VALUE = Decimal('0')


PLOT_SIZE_DIGITS = 5
PLOT_SIZE_DECIMAL_PLACES = 2
PLOT_SIZE_MIN_VALUE = Decimal('0.01')

DJANGO_SILK_ON = bool(int(os.getenv('DJANGO_SILK_ON', 0)))
DRF_SPECTACULAR_ON = bool(int(os.getenv('DRF_SPECTACULAR_ON', 0)))

AVATAR_DEFAULT_IMAGE = 'avatar.png'
AVATARS_SUBDIRECTORY = 'account/avatars/'
