import os

STRIPE_API_KEY = os.getenv('STRIPE_API_KEY')
STRIPE_WEBHOOK_SIGNING_SECRET = os.getenv('STRIPE_WEBHOOK_SIGNING_SECRET')

CHECKOUT_CURRENCY = 'pln'
CHECKOUT_MODE = 'payment'
CHECKOUT_SUCCESS_URL = 'http://localhost:4200/payment/success'
CHECKOUT_CANCEL_URL = 'http://localhost:4200/payment/cancel'
CHECKOUT_EXPIRATION = int(os.getenv('CHECKOUT_EXPIRATION_IN_SECONDS', 3600))

MAX_REFUND_TIME = 14
