# Generated by Django 5.1.3 on 2025-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Designates whether this account should be treated as anonymized.', verbose_name='IsAnonymized'),
        ),
    ]
